language: perl
perl:
 - "5.10"
 - "5.12"
 - "5.14"
 - "5.16"
script:
   - perl Build.PL && ./Build && cover -test
install: 
 - "sudo apt-get update"
 - "sudo apt-get install libdb-dev"
 - "cpanm -n --quiet --installdeps ."
 - "cpanm --quiet -n Devel::Cover::Report::Coveralls"
branches:
   only:
     - "feature/fixture-loader"
after_success:
   cover -report coveralls
