language: perl
perl:
 - "5.10"
 - "5.12"
 - "5.14"
 - "5.16"
before_script:
 - createdb -U postgres test_chado
env:
 - TC_DSN="dbi:Pg:dbname=test_chado"
 - TC_USER="postgres"
 - TC_PASSWORD=""
script:
   - perl Build.PL && ./Build && cover -test
install: 
 - "sudo apt-get update"
 - "sudo apt-get install libdb-dev"
 - "cpanm -n --quiet --installdeps ."
 - "cpanm --quiet -n Devel::Cover::Report::Coveralls DBD::Pg"
branches:
   only:
     - "develop"
     - "feature/basic-pg-backend"
after_success:
   cover -report coveralls
