---
abstract: 'Build,configure and test chado database backed modules and applications'
author:
  - 'Siddhartha Basu <biosidd@gmail.com>'
build_requires:
  Module::Build: 0.3601
  Test::Exception: 0.31
  Test::More: 0.94
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Chado
requires:
  Bio::Chado::Schema: 0.20000
  DBD::SQLite: 1.37
  File::Path: 2.08
  File::ShareDir: 1.02
  Graph: 0.94
  IPC::Cmd: 0.58
  Moo: 1.001
  MooX::InsideOut: 0.001002
  MooX::late: 0.009
  MooseX::Params::Validate: 0.14
  Path::Class: 0.18
  Test::DBIx::Class: 0.38
  Try::Tiny: 0.03
  XML::Twig: 3.35
  XML::XPath: 1.13
  YAML: 0.70
  namespace::autoclean: 0.11
  perl: 5.010
resources: {}
version: 1.0.0
